### ISSUE TITLE
Remote extensions not working

### ISSUE THREAD

**Issue by metalwanderer** [xaberus/vscode-remote-oss#5] opened 2023-01-02 12:57 UTC
Hi, first off: THANK YOU for your work enabling remote development on VSCodium! :smile:  I've been using this extension between Linux client and server for personal projects without issue.

However, I'm getting strange behavior with the extensions on my work machine when connected to the remote server.
Basic setup: Windows 11 host connected to WSL2 instance via localnet.  It opens the connection to the server without error and opens the workspace, but none of the extensions work.

Host:
```
Version: 1.74.2 (system setup)
Release: 22355
Commit: d2c422ca15f1fbc976eed3e02e3392bbb39c5824
Date: 2022-12-21T18:33:19.960Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
```

Remote:
```
~$ echo $(curl -s --unix-socket lib/vscodium-server/socket http://localhost/version)
d2c422ca15f1fbc976eed3e02e3392bbb39c5824
```

My connection setup is a little overengineered (systemd socket linked to `$HOME/lib/vscodium-server/socket` via `systemd-socket-proxyd`), but that part seems to work fine.  But:
- all of my local extensions (except for `Remote (OSS)`) are marked with *Reload Required*
  - reloading VSCodium doesn't help
- all of my remote extensions are grayed out
- no extension settings are available on remote side
- not able to use the installed extensions (ie `Ansible`)

![image](https://user-images.githubusercontent.com/2190808/210231003-07df3931-7c14-4768-913d-df069a09b93c.png) ![image](https://user-images.githubusercontent.com/2190808/210231143-56620e0b-ba9c-411e-8687-0416da5f1cdd.png)
![image](https://user-images.githubusercontent.com/2190808/210231272-4cd9f62a-9c0d-4d66-8a41-5e0613d9a935.png)

`Ansible` not available

<details>
<summary>
Remote Server logs:
</summary>
<code>
2023-01-02 12:51:05.815 [info] [<unknown>][4e8cdfda][ManagementConnection] New connection established.
2023-01-02 12:51:05.824 [info] [<unknown>][2f28173a][ExtensionHostConnection] New connection established.
2023-01-02 12:51:05.827 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944> Launched Extension Host Process.
2023-01-02 12:51:06.346 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.clojure` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.coffeescript` is already registered
Extension `vscode.cpp` is already registered
Extension `vscode.csharp` is already registered
Extension `vscode.css` is already registered
Extension `vscode.dart` is already registered
Extension `vscode.diff` is already registered
Extension `vscode.docker` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.fsharp` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.github-authentication` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.go` is already registered
Extension `vscode.groovy` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.hlsl` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.html` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.ini` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.ipynb` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.java` is already registered
Extension `vscode.javascript` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.json` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.julia` is already registered
Extension `vscode.latex` is already registered
Extension `vscode.less` is already registered
Extension `vscode.log` is already registered
Extension `vscode.lua` is already registered
Extension `vscode.make` is already registered
Extension `vscode.markdown` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.media-preview` is already registered
Extension `vscode.microsoft-authentication` is already registered
Extension `ms-vscode.js-debug-companion` is already registered
Extension `vscode.builtin-notebook-renderers` is already registered
Extension `vscode.objective-c` is already registered
Extension `vscode.perl` is already registered
Extension `vscode.php` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.powershell` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.pug` is already registered
Extension `vscode.python` is already registered
Extension `vscode.r` is already registered
Extension `vscode.razor` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.restructuredtext` is already registered
Extension `vscode.ruby` is already registered
Extension `vscode.rust` is already registered
Extension `vscode.scss` is already registered
Extension `vscode.shaderlab` is already registered
Extension `vscode.shellscript` is already registered
Extension `vscode.simple-browser` is already registered
Extension `vscode.sql` is already registered
Extension `vscode.swift` is already registered
Extension `vscode.theme-abyss` is already registered
Extension `vscode.theme-defaults` is already registered
Extension `vscode.theme-kimbie-dark` is already registered

2023-01-02 12:51:06.347 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.theme-monokai` is already registered
Extension `vscode.theme-monokai-dimmed` is already registered
Extension `vscode.theme-quietlight` is already registered
Extension `vscode.theme-red` is already registered
Extension `vscode.vscode-theme-seti` is already registered
Extension `vscode.theme-solarized-dark` is already registered
Extension `vscode.theme-solarized-light` is already registered
Extension `vscode.theme-tomorrow-night-blue` is already registered

2023-01-02 12:51:06.348 [info] [<unknown>][2f28173a][ExtensionHostConnection] <1944><stderr> Extension `vscode.typescript` is already registered
Extension `vscode.vb` is already registered
Extension `vscode.xml` is already registered
Extension `vscode.yaml` is already registered
Extension `jeanp413.open-remote-ssh` is already registered
Extension `xaberus.remote-oss` is already registered
</code>
</details>

<details>
<summary>
Remote Server logs (previous runs - `ansible` extension shows up):
</summary>
<code>
2023-01-02 12:13:27.767 [info] 

2023-01-02 12:13:27.767 [info] Extension host agent started.
2023-01-02 12:13:27.779 [info] Started initializing default profile extensions in extensions installation folder. file:///home/user/.vscodium-server/extensions
2023-01-02 12:13:27.793 [info] [<unknown>][bed7eee2][ManagementConnection] New connection established.
2023-01-02 12:13:27.798 [info] [<unknown>][75bc593d][ExtensionHostConnection] New connection established.
2023-01-02 12:13:27.806 [info] [<unknown>][75bc593d][ExtensionHostConnection] <1836> Launched Extension Host Process.
2023-01-02 12:13:27.811 [info] Completed initializing default profile extensions in extensions installation folder. file:///home/user/.vscodium-server/extensions
2023-01-02 12:13:29.410 [info] [<unknown>][75bc593d][ExtensionHostConnection] <1836><stderr> Extension `vscode.clojure` is already registered

2023-01-02 12:13:29.411 [info] [<unknown>][75bc593d][ExtensionHostConnection] <1836><stderr> Extension `vscode.coffeescript` is already registered
Extension `vscode.cpp` is already registered
Extension `vscode.csharp` is already registered
Extension `vscode.css` is already registered
Extension `vscode.dart` is already registered
Extension `vscode.diff` is already registered

2023-01-02 12:13:29.411 [info] [<unknown>][75bc593d][ExtensionHostConnection] <1836><stderr> Extension `vscode.docker` is already registered
Extension `vscode.fsharp` is already registered
Extension `vscode.github-authentication` is already registered
Extension `vscode.go` is already registered
Extension `vscode.groovy` is already registered
Extension `vscode.hlsl` is already registered

2023-01-02 12:13:29.411 [info] [<unknown>][75bc593d][ExtensionHostConnection] <1836><stderr> Extension `vscode.html` is already registered
Extension `vscode.ini` is already registered
Extension `vscode.ipynb` is already registered
Extension `vscode.java` is already registered
Extension `vscode.javascript` is already registered

2023-01-02 12:13:29.411 [info] [<unknown>][75bc593d][ExtensionHostConnection] <1836><stderr> Extension `vscode.json` is already registered
Extension `vscode.julia` is already registered
Extension `vscode.latex` is already registered
Extension `vscode.less` is already registered
Extension `vscode.log` is already registered
Extension `vscode.lua` is already registered
Extension `vscode.make` is already registered
Extension `vscode.markdown` is already registered

2023-01-02 12:13:29.411 [info] [<unknown>][75bc593d][ExtensionHostConnection] <1836><stderr> Extension `vscode.media-preview` is already registered
Extension `vscode.microsoft-authentication` is already registered
Extension `ms-vscode.js-debug-companion` is already registered
Extension `vscode.builtin-notebook-renderers` is already registered
Extension `vscode.objective-c` is already registered
Extension `vscode.perl` is already registered
Extension `vscode.php` is already registered
Extension `vscode.powershell` is already registered
Extension `vscode.pug` is already registered
Extension `vscode.python` is already registered
Extension `vscode.r` is already registered
Extension `vscode.razor` is already registered
Extension `vscode.restructuredtext` is already registered
Extension `vscode.ruby` is already registered
Extension `vscode.rust` is already registered
Extension `vscode.scss` is already registered
Extension `vscode.shaderlab` is already registered
Extension `vscode.shellscript` is already registered
Extension `vscode.simple-browser` is already registered
Extension `vscode.sql` is already registered
Extension `vscode.swift` is already registered
Extension `vscode.theme-abyss` is already registered

2023-01-02 12:13:29.412 [info] [<unknown>][75bc593d][ExtensionHostConnection] <1836><stderr> Extension `vscode.theme-defaults` is already registered
Extension `vscode.theme-kimbie-dark` is already registered
Extension `vscode.theme-monokai` is already registered
Extension `vscode.theme-monokai-dimmed` is already registered
Extension `vscode.theme-quietlight` is already registered
Extension `vscode.theme-red` is already registered
Extension `vscode.vscode-theme-seti` is already registered
Extension `vscode.theme-solarized-dark` is already registered
Extension `vscode.theme-solarized-light` is already registered
Extension `vscode.theme-tomorrow-night-blue` is already registered
Extension `vscode.typescript` is already registered
Extension `vscode.vb` is already registered
Extension `vscode.xml` is already registered
Extension `vscode.yaml` is already registered
Extension `xaberus.remote-oss` is already registered

2023-01-02 12:14:42.328 [info] Getting Manifest... ms-kubernetes-tools.vscode-kubernetes-tools
2023-01-02 12:14:42.329 [info] Getting Manifest... mads-hartmann.bash-ide-vscode
2023-01-02 12:14:42.329 [info] Getting Manifest... redhat.vscode-commons
2023-01-02 12:14:42.329 [info] Getting Manifest... redhat.ansible
2023-01-02 12:14:43.378 [info] Installing extension: redhat.vscode-commons
2023-01-02 12:14:43.413 [info] Installing extension: mads-hartmann.bash-ide-vscode
2023-01-02 12:14:43.464 [info] Installing extension: ms-kubernetes-tools.vscode-kubernetes-tools
2023-01-02 12:14:43.568 [info] Installing extension: redhat.ansible
2023-01-02 12:14:44.060 [info] Getting Manifest... redhat.vscode-yaml
2023-01-02 12:14:44.128 [info] Getting Manifest... ms-python.python
2023-01-02 12:14:44.464 [info] Extracted extension to /home/user/.vscodium-server/extensions/.fd0c9c70-d48b-45c4-987f-cb2d304bdd3f: redhat.vscode-commons
2023-01-02 12:14:44.471 [info] Renamed to /home/user/.vscodium-server/extensions/redhat.vscode-commons-0.0.6-universal
2023-01-02 12:14:44.473 [info] Extracting completed. redhat.vscode-commons
2023-01-02 12:14:44.481 [info] Extension installed successfully: redhat.vscode-commons
2023-01-02 12:14:44.634 [info] Installing extension: redhat.vscode-yaml ms-kubernetes-tools.vscode-kubernetes-tools
2023-01-02 12:14:45.262 [info] Getting Manifest... ms-toolsai.jupyter
2023-01-02 12:14:45.759 [info] Extracted extension to /home/user/.vscodium-server/extensions/.bf4906af-8da7-40f8-a3e8-b659c9547549: redhat.vscode-yaml
2023-01-02 12:14:45.760 [info] Extracted extension to /home/user/.vscodium-server/extensions/.5eb10f20-1510-4277-9b5d-4fde6cca1772: mads-hartmann.bash-ide-vscode
2023-01-02 12:14:45.766 [info] Renamed to /home/user/.vscodium-server/extensions/redhat.vscode-yaml-1.10.1-universal
2023-01-02 12:14:45.769 [info] Extracting completed. redhat.vscode-yaml
2023-01-02 12:14:45.770 [info] Renamed to /home/user/.vscodium-server/extensions/mads-hartmann.bash-ide-vscode-1.23.0-universal
2023-01-02 12:14:45.772 [info] Extracting completed. mads-hartmann.bash-ide-vscode
2023-01-02 12:14:45.802 [info] Extension installed successfully: mads-hartmann.bash-ide-vscode
2023-01-02 12:14:46.417 [info] Getting Manifest... ms-toolsai.jupyter-renderers
2023-01-02 12:14:46.998 [info] Getting Manifest... ms-toolsai.jupyter-keymap
2023-01-02 12:14:47.024 [info] Extracted extension to /home/user/.vscodium-server/extensions/.6d4c022c-9935-43d1-b888-4f99b6a00ebe: ms-kubernetes-tools.vscode-kubernetes-tools
2023-01-02 12:14:47.030 [info] Renamed to /home/user/.vscodium-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.11-universal
2023-01-02 12:14:47.032 [info] Extracting completed. ms-kubernetes-tools.vscode-kubernetes-tools
2023-01-02 12:14:47.039 [info] Extension installed successfully: redhat.vscode-yaml
2023-01-02 12:14:47.039 [info] Extension installed successfully: ms-kubernetes-tools.vscode-kubernetes-tools
2023-01-02 12:14:47.599 [info] Getting Manifest... ms-toolsai.vscode-jupyter-cell-tags
2023-01-02 12:14:48.189 [info] Getting Manifest... ms-toolsai.vscode-jupyter-slideshow
2023-01-02 12:14:48.735 [info] Getting Manifest... ms-python.isort
2023-01-02 12:14:49.259 [info] Getting Manifest... redhat.vscode-yaml
2023-01-02 12:14:49.869 [info] Installing extension: ms-python.python redhat.ansible
2023-01-02 12:14:49.869 [info] Installing extension: ms-toolsai.jupyter redhat.ansible
2023-01-02 12:14:49.869 [info] Installing extension: ms-toolsai.jupyter-renderers redhat.ansible
2023-01-02 12:14:49.869 [info] Installing extension: ms-toolsai.jupyter-keymap redhat.ansible
2023-01-02 12:14:49.869 [info] Installing extension: ms-toolsai.vscode-jupyter-cell-tags redhat.ansible
2023-01-02 12:14:49.870 [info] Installing extension: ms-toolsai.vscode-jupyter-slideshow redhat.ansible
2023-01-02 12:14:49.870 [info] Installing extension: ms-python.isort redhat.ansible
2023-01-02 12:14:50.816 [info] Extracted extension to /home/user/.vscodium-server/extensions/.706c18c0-1882-44b7-8f7b-6d50c4150324: ms-toolsai.jupyter-keymap
2023-01-02 12:14:50.823 [info] Renamed to /home/user/.vscodium-server/extensions/ms-toolsai.jupyter-keymap-1.0.0-universal
2023-01-02 12:14:50.824 [info] Extracting completed. ms-toolsai.jupyter-keymap
2023-01-02 12:14:50.890 [info] Extracted extension to /home/user/.vscodium-server/extensions/.f37caa0a-371e-4606-add9-5de6f5047a71: ms-toolsai.vscode-jupyter-slideshow
2023-01-02 12:14:50.895 [info] Renamed to /home/user/.vscodium-server/extensions/ms-toolsai.vscode-jupyter-slideshow-0.1.5-universal
2023-01-02 12:14:50.897 [info] Extracting completed. ms-toolsai.vscode-jupyter-slideshow
2023-01-02 12:14:52.400 [info] Extracted extension to /home/user/.vscodium-server/extensions/.4706bc46-c2c1-4001-a995-367dee0f088a: ms-toolsai.jupyter-renderers
2023-01-02 12:14:52.425 [info] Renamed to /home/user/.vscodium-server/extensions/ms-toolsai.jupyter-renderers-1.0.12-universal
2023-01-02 12:14:52.427 [info] Extracting completed. ms-toolsai.jupyter-renderers
2023-01-02 12:14:53.920 [info] Extracted extension to /home/user/.vscodium-server/extensions/.7a70413b-0a7b-4794-a72c-61dd9c0a8970: ms-toolsai.jupyter
2023-01-02 12:14:53.939 [info] Renamed to /home/user/.vscodium-server/extensions/ms-toolsai.jupyter-2022.10.110-universal
2023-01-02 12:14:53.956 [info] Extracting completed. ms-toolsai.jupyter
2023-01-02 12:14:53.961 [info] Extracted extension to /home/user/.vscodium-server/extensions/.70c7a656-1a88-4b74-9312-1e9617ad8fd7: ms-toolsai.vscode-jupyter-cell-tags
2023-01-02 12:14:53.967 [info] Renamed to /home/user/.vscodium-server/extensions/ms-toolsai.vscode-jupyter-cell-tags-0.1.6-universal
2023-01-02 12:14:53.970 [info] Extracting completed. ms-toolsai.vscode-jupyter-cell-tags
2023-01-02 12:14:55.672 [info] Extracted extension to /home/user/.vscodium-server/extensions/.c4fa1889-abda-4826-a306-5dcf2bfeb6ce: ms-python.python
2023-01-02 12:14:55.695 [info] Renamed to /home/user/.vscodium-server/extensions/ms-python.python-2022.20.1-universal
2023-01-02 12:14:55.703 [info] Extracting completed. ms-python.python
2023-01-02 12:14:56.877 [info] Extracted extension to /home/user/.vscodium-server/extensions/.e60fc1ee-53ba-4a61-80d9-1a03b94f1f18: ms-python.isort
2023-01-02 12:14:56.884 [info] Renamed to /home/user/.vscodium-server/extensions/ms-python.isort-2022.8.0-universal
2023-01-02 12:14:56.886 [info] Extracting completed. ms-python.isort
2023-01-02 12:14:57.813 [info] Extracted extension to /home/user/.vscodium-server/extensions/.2dfb18e5-f609-45c6-b693-b76d73921673: redhat.ansible
2023-01-02 12:14:57.819 [info] Renamed to /home/user/.vscodium-server/extensions/redhat.ansible-1.0.90-universal
2023-01-02 12:14:57.822 [info] Extracting completed. redhat.ansible
2023-01-02 12:14:57.829 [info] Extension installed successfully: ms-toolsai.jupyter-keymap
2023-01-02 12:14:57.829 [info] Extension installed successfully: ms-toolsai.vscode-jupyter-slideshow
2023-01-02 12:14:57.829 [info] Extension installed successfully: ms-toolsai.jupyter-renderers
2023-01-02 12:14:57.829 [info] Extension installed successfully: ms-toolsai.jupyter
2023-01-02 12:14:57.829 [info] Extension installed successfully: ms-toolsai.vscode-jupyter-cell-tags
2023-01-02 12:14:57.829 [info] Extension installed successfully: ms-python.python
2023-01-02 12:14:57.829 [info] Extension installed successfully: ms-python.isort
2023-01-02 12:14:57.829 [info] Extension installed successfully: redhat.ansible
2023-01-02 12:15:08.411 [info] Uninstalling extension from the profile: ms-toolsai.jupyter@2022.10.110 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:15:08.443 [info] Uninstalling extension from the profile: ms-toolsai.jupyter-keymap@1.0.0 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:15:08.443 [info] Uninstalling extension from the profile: ms-toolsai.jupyter-renderers@1.0.12 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:15:08.443 [info] Uninstalling extension from the profile: ms-toolsai.vscode-jupyter-cell-tags@0.1.6 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:15:08.443 [info] Uninstalling extension from the profile: ms-toolsai.vscode-jupyter-slideshow@0.1.5 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:15:08.491 [info] Marked extension as uninstalled ms-toolsai.jupyter-2022.10.110-universal
2023-01-02 12:15:08.491 [info] Marked extension as uninstalled ms-toolsai.jupyter-keymap-1.0.0-universal
2023-01-02 12:15:08.491 [info] Marked extension as uninstalled ms-toolsai.jupyter-renderers-1.0.12-universal
2023-01-02 12:15:08.516 [info] Marked extension as uninstalled ms-toolsai.vscode-jupyter-cell-tags-0.1.6-universal
2023-01-02 12:15:08.540 [info] Marked extension as uninstalled ms-toolsai.vscode-jupyter-slideshow-0.1.5-universal
2023-01-02 12:15:08.878 [info] Successfully uninstalled extension from the profile ms-toolsai.jupyter@2022.10.110 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:15:08.899 [info] Successfully uninstalled extension from the profile ms-toolsai.jupyter-keymap@1.0.0 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:15:08.911 [info] Successfully uninstalled extension from the profile ms-toolsai.vscode-jupyter-slideshow@0.1.5 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:15:08.917 [info] Successfully uninstalled extension from the profile ms-toolsai.vscode-jupyter-cell-tags@0.1.6 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:15:08.918 [info] Successfully uninstalled extension from the profile ms-toolsai.jupyter-renderers@1.0.12 file:///home/user/.vscodium-server/data/User/extensions.json
2023-01-02 12:24:17.160 [info] [<unknown>][bed7eee2][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2023-01-02 12:24:17.164 [info] [<unknown>][75bc593d][ExtensionHostConnection] <1836> Extension Host Process exited with code: 0, signal: null.
2023-01-02 12:32:38.140 [info] [<unknown>][dc73aa11][ManagementConnection] New connection established.
2023-01-02 12:32:38.153 [info] [<unknown>][41ac2103][ExtensionHostConnection] New connection established.
2023-01-02 12:32:38.158 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877> Launched Extension Host Process.
2023-01-02 12:32:39.810 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.clojure` is already registered

2023-01-02 12:32:39.810 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.coffeescript` is already registered
Extension `vscode.cpp` is already registered
Extension `vscode.csharp` is already registered
Extension `vscode.css` is already registered
Extension `vscode.dart` is already registered
Extension `vscode.diff` is already registered
Extension `vscode.docker` is already registered
Extension `vscode.fsharp` is already registered

2023-01-02 12:32:39.810 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.github-authentication` is already registered

2023-01-02 12:32:39.810 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.go` is already registered
Extension `vscode.groovy` is already registered

2023-01-02 12:32:39.810 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.hlsl` is already registered
Extension `vscode.html` is already registered
Extension `vscode.ini` is already registered

2023-01-02 12:32:39.810 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.ipynb` is already registered
Extension `vscode.java` is already registered
Extension `vscode.javascript` is already registered
Extension `vscode.json` is already registered
Extension `vscode.julia` is already registered
Extension `vscode.latex` is already registered
Extension `vscode.less` is already registered
Extension `vscode.log` is already registered
Extension `vscode.lua` is already registered
Extension `vscode.make` is already registered
Extension `vscode.markdown` is already registered
Extension `vscode.media-preview` is already registered

2023-01-02 12:32:39.811 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.microsoft-authentication` is already registered
Extension `ms-vscode.js-debug-companion` is already registered
Extension `vscode.builtin-notebook-renderers` is already registered
Extension `vscode.objective-c` is already registered
Extension `vscode.perl` is already registered
Extension `vscode.php` is already registered
Extension `vscode.powershell` is already registered

2023-01-02 12:32:39.811 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.pug` is already registered
Extension `vscode.python` is already registered
Extension `vscode.r` is already registered
Extension `vscode.razor` is already registered
Extension `vscode.restructuredtext` is already registered
Extension `vscode.ruby` is already registered
Extension `vscode.rust` is already registered
Extension `vscode.scss` is already registered
Extension `vscode.shaderlab` is already registered
Extension `vscode.shellscript` is already registered
Extension `vscode.simple-browser` is already registered

2023-01-02 12:32:39.811 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.sql` is already registered
Extension `vscode.swift` is already registered
Extension `vscode.theme-abyss` is already registered
Extension `vscode.theme-defaults` is already registered
Extension `vscode.theme-kimbie-dark` is already registered
Extension `vscode.theme-monokai` is already registered
Extension `vscode.theme-monokai-dimmed` is already registered
Extension `vscode.theme-quietlight` is already registered
Extension `vscode.theme-red` is already registered
Extension `vscode.vscode-theme-seti` is already registered
Extension `vscode.theme-solarized-dark` is already registered
Extension `vscode.theme-solarized-light` is already registered
Extension `vscode.theme-tomorrow-night-blue` is already registered
Extension `vscode.typescript` is already registered

2023-01-02 12:32:39.811 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877><stderr> Extension `vscode.vb` is already registered
Extension `vscode.xml` is already registered
Extension `vscode.yaml` is already registered
Extension `xaberus.remote-oss` is already registered

2023-01-02 12:32:41.444 [info] Getting Manifest... redhat.ansible
2023-01-02 12:32:42.482 [info] Installing extension: redhat.ansible
2023-01-02 12:32:42.915 [info] Getting Manifest... ms-python.python
2023-01-02 12:32:43.578 [info] Getting Manifest... redhat.vscode-yaml
2023-01-02 12:32:45.090 [info] Extracted extension to /home/user/.vscodium-server/extensions/.452ae28c-e36f-40cc-bd1b-5821db2655c6: redhat.ansible
2023-01-02 12:32:45.097 [info] Renamed to /home/user/.vscodium-server/extensions/redhat.ansible-1.1.34-universal
2023-01-02 12:32:45.100 [info] Extracting completed. redhat.ansible
2023-01-02 12:32:45.107 [info] Extension installed successfully: redhat.ansible
2023-01-02 12:32:45.124 [info] Marked extension as uninstalled redhat.ansible-1.0.90-universal
2023-01-02 12:33:29.197 [info] [<unknown>][dc73aa11][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2023-01-02 12:33:29.201 [info] [<unknown>][41ac2103][ExtensionHostConnection] <1877> Extension Host Process exited with code: 0, signal: null.
</code>
</details>

VSCodium was installed with Chocolatey.  I've tried wiping out the user files (`.vscod*` dirs, etc.) on both sides, problem always recurs when I connect remotely.  When a window has a local directory open: everything works as expected.

I have nearly the identical setup on my personal machine (same VSCodium and REH versions, same extensions, same connection logic) and it works flawlessly there - the big difference is Windows 11 on the host and WSL2 on the remote.

Would love to get this working on my work machine! :smile:
Thanks again! 👍

**Comment by kovdan01** [comment] 2023-01-02 16:33
I'm also facing the issue. VSCodium 1.74.2 client running Windows 10 22H2, remote running Arch Linux. The issue is also reproduced with a similar extension https://github.com/jeanp413/open-remote-ssh/

**Comment by kovdan01** [comment] 2023-01-02 18:51
Update: I was able to resolve the issue by rolling back to VSCodium 1.73.1. @metalwanderer maybe this will also work for you.

**Comment by xaberus** [comment] 2023-01-02 21:23
I might be missing something, but unfortunetely I cannot reproduce this problem on linux @d2c422c (1.74.2) both host and remote, (both machines are running basically the same Fedora distribution). I.e. I was able to install `Ansible` on the remote and it showed up in the menu. Isort & YAML extensions are also running. 

Have you tried reinstalling the extensions? Lately Codium started to get stuck on some extensions in my install so maybe this is related? Is there something else specific to you installations? They only real difference I am seeing is the number of extensions :smile: (I have ~8 active...)

what does the following say?
```bash
codium-server --show-versions --list-extensions
```

**Comment by metalwanderer** [comment] 2023-01-03 16:46
@xaberus Yes, I also can't reproduce / don't see the issue on my personal setup between two native Debian/bullseye machines - there everything works fine.  But the issue is consistent between Windows 11 Enterprise 21H2 host and WSL2(Debian/bullseye) remote.

The only real difference between my personal (which works fine) and work (which doesn't) setups is Windows... whether it's caused by the Windows host or the WSL environment for the remote (or both?), I've got no clue. 😕 

I've tried reinstalling extensions multiple times, both on local and remote side - both using the GUI uninstall option and by erasing the files from their respective locations.  Also tried reinstalling VSCodium. 😄 

Looks like the extensions are present on the remote:
```
$ lib/vscodium-server/bin/current/bin/codium-server --show-versions --list-extensions
mads-hartmann.bash-ide-vscode@1.23.0
ms-kubernetes-tools.vscode-kubernetes-tools@1.3.11
ms-python.isort@2022.8.0
ms-python.python@2022.20.1
redhat.ansible@1.1.34
redhat.vscode-commons@0.0.6
redhat.vscode-yaml@1.10.1
```
That's exactly the list of extensions which should be installed.

**Comment by metalwanderer** [comment] 2023-01-03 17:12
> Update: I was able to resolve the issue by rolling back to VSCodium 1.73.1. @metalwanderer maybe this will also work for you.

Thanks for the tip, @kovdan01 , that also works for me! 😄 

@xaberus I experienced the same issues on 1.74.2.22355 and 1.74.1.22349, but it works on 1.73.1.22314 (forgot to test 1.74.0)

**Comment by xaberus** [comment] 2023-01-04 05:51
I was able to reproduce the bug using a windows client. As far as I understand it is the same [issue](https://github.com/jeanp413/open-remote-ssh/issues/44) open-remote-ssh users are experiencing. My development setup on windows is quite anemic, so I am not sure, when I will be able to bisect this... 

From the reply by @jeanp413 the issue seems to be VSCodium specific, but I had not time to reproduce it yet. Can maybe one of you file a bug report on VSCodium and reference both issues there, please?

**Comment by xaberus** [comment] 2023-01-05 06:44
I take the last back. After compiling the stock OSS 1.74.0 release I can reproduce the issue there as well. So this is VSCode-OSS specific... I do not have the time to bisect the ~1k commits right now...

**Comment by metalwanderer** [comment] 2023-01-05 16:04
Should I still file an issue with VSCodium? Or rather file with VSCode-OSS?  I'm unclear whether the REH is supported by VSCode-OSS in this use case.

**Comment by xaberus** [comment] 2023-01-07 09:09
@metalwanderer Just a heads up: the discussion is still ongoing over in the [other](https://github.com/jeanp413/open-remote-ssh/issues/44) extensions issue tracker. I am not still sure about the cause, but we might have found a minimization bug in the build system.

**Comment by metalwanderer** [comment] 2023-01-07 11:26
@xaberus thanks for the update... I'll wait to see what your investigation in that ticket leads to.  Thanks for the efforts!

**Comment by xaberus** [comment] 2023-01-07 15:14
@daiyam just updated the build, and from my testing [1.74.2.23007](https://github.com/VSCodium/vscodium/releases/tag/1.74.2.23007) should not suffer from this issue. Can you test it on your side, please?

**Comment by metalwanderer** [comment] 2023-01-07 15:44
@xaberus not sure if you meant to post that message to the other tracker, or just @'ed the wrong person 😉 
but, I just tested 1.74.23007 on my work setup - everything looks good! 👍 
Thanks for looking out! 😄

**Comment by xaberus** [comment] 2023-01-07 17:04
I meant that [daiyam](https://github.com/daiyam), the maintainer of VSCodium, uploaded a build that fixed the issue. Sorry for the confusion. (A stray @ so to speak...) 
I guess we can close the issue for now? Still not quite sure whether or not to file a bug report to upstream VSCode-OSS...

**Comment by metalwanderer** [comment] 2023-01-07 17:19
Issue is resolved from my point of view.  It seems to me VSCode-OSS already fixed the root cause - they might not be aware of how it manifested here, but the report would essentially be for a bug already fixed, wouldn't it?

I don't personally have enough experience fielding public bug reports to know if they'd appreciate it.  Would you, in their place?

Happy to file an issue over there if you think it's constructive.  I can link this issue as well as the one on remote-ssh.

**Comment by xaberus** [comment] 2023-01-07 17:41
I just filed a report - now I guess I will find out :laughing:. I will keep this open until I have a reply from upstream, if it is alright with you (as a reminder for myself...).

**Comment by xaberus** [comment] 2023-04-08 20:33
The issue seems to be solved upstream. Therefore I will close this issue for now...

**Closed by xaberus** 2023-04-08 20:33 UTC
